workspace:
  base: /var/www/owncloud
  path: onwcloud-sdk

branches:
  - master

pipeline:
  increment-version:
    image: node:11
    commands:
      - yarn version --no-git-tag-version --new-version 1.0.0-${DRONE_BUILD_NUMBER}
    when:
      event: [push]

  build-docs:
    image: node:11
    commands:
      - yarn install
      - yarn build:docs

  build-system:
    image: node:11
    commands:
      - yarn install
      - yarn lint
      - yarn build:system

  install-server:
    image: owncloudci/core
    version: ${OC_VERSION=daily-master-qa}
    pull: true
    db_type: ${DB_TYPE=sqlite}
    db_name: ${DB_NAME=sqlite}
    db_host: ${DB_TYPE=sqlite}
    db_username: autotest
    db_password: owncloud
    core_path: /var/www/owncloud/

  configure-server:
    image: owncloudci/php:${PHP_VERSION=7.1}
    pull: true
    commands:
      - cd /var/www/owncloud/
      - php occ config:system:set trusted_domains 1 --value=owncloud
      - php occ config:system:set cors.allowed-domains 0 --value=http://localhost:9876
      - php occ log:manage --level 0
      - php occ config:list
      - chown www-data * -R

  owncloud-log:
    image: owncloud/ubuntu:16.04
    detach: true
    pull: true
    commands:
      - tail -f /var/www/owncloud/data/owncloud.log

  wait-for-owncloud:
    image: owncloudci/php:${PHP_VERSION=7.1}
    pull: true
    commands:
      - wait-for-it -t 300 owncloud:80

  test:
    image: owncloudci/chromium
    commands:
      - cp tests/config/config.drone.json tests/config/config.json
      - yarn test-drone

  codecov:
    image: plugins/codecov:2
    secrets: [codecov_token]
    pull: true
    files:
      - '*.info'
    paths:
      - coverage
    when:
      event: [push, pull_request]

  publish-docs:
    image: plugins/gh-pages:1
    secrets: [github_username, github_password]
    pages_directory: docs
    when:
      event: [push]
      matrix:
        PUBLISH: true

  publish-system:
    image: plugins/npm:1
    secrets: [npm_username, npm_email, npm_token]
    when:
      event: [push]
      matrix:
        PUBLISH: true

services:
  owncloud:
    image: owncloudci/php:${PHP_VERSION=7.1}
    pull: true
    environment:
      - APACHE_WEBROOT=/var/www/owncloud/
    command: [ "/usr/local/bin/apachectl", "-e", "debug", "-D", "FOREGROUND" ]

matrix:
  include:
    - PUBLISH: false
      OC_VERSION: daily-master-qa
    - PUBLISH: true
      OC_VERSION: daily-stable10-qa
